name: Testes

on:
  push:
  pull_request:

jobs:
  testes-unitarios:
    name: Testes unitários (Minitest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
      - run: bundle install
      - run: bundle exec rake test
